### ISSUE TITLE
We can not build transformers anymore without sentencepiece after 2.2.0

### ISSUE THREAD

**Issue by roccqqck** [conda-forge/transformers-feedstock#3]
After transformers 2.2.0,
we can not build transformers anymore without sentencepiece.

If anyone who knows how to build sentencepiece into conda-forge would be much helpful.

https://github.com/google/sentencepiece
https://pypi.org/project/sentencepiece/

**Comment by setu4993** [comment]
Trying to get `sentencepiece` onto `conda-forge` with this: https://github.com/conda-forge/staged-recipes/pull/10580

Any help appreciated.

**Comment by setu4993** [comment]
Resolved.
