### ISSUE TITLE
Depends on wrong version of tokenizers

### ISSUE THREAD

**Issue by sfschouten** [conda-forge/transformers-feedstock#81]
Hi there,

It looks like the recipe still specifies an older version of the tokenizers package.
https://github.com/conda-forge/transformers-feedstock/blob/4f30974a71367bd124b79e71817b7543ff843f1d/recipe/meta.yaml#L26

Since version 4.16 the official dependency no longer requires the version to be below 11  https://github.com/huggingface/transformers/pull/14941.

Hope this is the right place to report something like this.

Cheers, Stefan

**Comment by setu4993** [comment]
Thanks for the callout. I started fixing it in #82 (but #80 would also fix it). Both seem to be failing because of a `libssl.so` error which I'm not sure how to fix.

**Comment by setu4993** [comment]
Thanks for raising, fixed in #80.
